import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 此代码在 Node.js 中运行 - 不要在此使用客户端代码（浏览器 API、JSX...）

/**
 * 创建侧边栏使您能够：
 - 创建有序的文档组
 - 为该组的每个文档渲染侧边栏
 - 提供上一个/下一个导航

 侧边栏可以从文件系统生成，或在此处明确定义。

 创建尽可能多的侧边栏。
 */
const sidebars: SidebarsConfig = {
  // 默认情况下，Docusaurus 从 docs 文件夹结构生成侧边栏
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 但您可以手动创建侧边栏
  tutorialSidebar: [
    'intro',
    'release-notes',
    'getting-started',
    {
      type: 'category',
      label: 'Database Setup',
      items: [
        'sqlite-setup',
        'sql-server-setup',
        'postgresql-setup',
        'connection-reference',
      ],
    },
    {
      type: 'category',
      label: 'Usage',
      items: [
        'database-tools',
        'usage-examples',
      ],
    },
    // AI Courses section
    {
      type: 'category',
      label: 'AI Courses',
      items: [
        'ai-courses/AIAgents',
        'ai-courses/GenAICourse',
        'ai-courses/MachineLearning',
      ],
    },
  ],
};

export default sidebars;
